Web/Areas/Administrator/Controllers/ImportController.cs
using Entities.DTOs;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml;
using Services.Import;
using Services.Product;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Areas.Administrator.Controllers
{
    [Area("Administrator")]
    public class ImportController : BaseController
    {
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IProductService productService;
        private readonly IImportService importService;

        public ImportController(IWebHostEnvironment _webHostEnvironment, IProductService _productService, IImportService _importService)
        {
            this.webHostEnvironment = _webHostEnvironment;
            this.productService = _productService;
            this.importService = _importService;
        }

        public IActionResult Index(int page = 1, int size = 10)
        {
            var model = importService.GetImportViewModels();
            ViewBag.CountRecord = model.Count();
            ViewBag.CurrentPage = page;
            ViewBag.CurrentSize = size;
            return View(model.Skip((page - 1) * size).Take(size));
        }

        [HttpGet]
        public IActionResult ImportProduct()
        {
            ViewBag.ListImportProduct = productService.GetAllImportProduct();
            return View();
        }

        [HttpPost]
        public IActionResult ImportProduct(string jsonString)
        {
            try
            {
                //Declare the variables used in Export Excel
                string fileName = @"\excel\Phiếu-nhập-hàng-" + DateTime.Now.ToString("MM-dd-yyyy-HH-mm-ss") + "-" + Guid.NewGuid().ToString() + ".xlsx";
                ExcelPackage pkg = new ExcelPackage(new System.IO.FileInfo(webHostEnvironment.WebRootPath + fileName));
                var ws = pkg.Workbook.Worksheets.Add("Phiếu-nhập-hàng-" + DateTime.Now.ToString("MM-dd-yyyy-HH-mm-ss"));
                int startRow = 7;
                int totalQuantity = 0;
                decimal totalPrice = 0;
                int countProducts = 0;
                //
                var ListProduct = JsonConvert.DeserializeObject<List<ImportProductViewModel>>(jsonString);

                ws.Cells["A1:G1"].Merge = true;
                ws.Cells["A2:G2"].Merge = true;
                ws.Cells["A3:G3"].Merge = true;
                ws.Cells["A4:G4"].Merge = true;
                ws.Cells["A5:G5"].Merge = true;
                ws.Cells["A1:G1"].Value = "Người Nhập: " + HttpContext.Session.GetString("user");
                ws.Cells["A2:G2"].Value = "Ngày Nhập:  " + DateTime.Now.ToString("MM-dd-yyyy-HH-mm-ss");

                ws.Cells[6, 1].Value = "STT";
                ws.Cells[6, 2].Value = "Mã sản phẩm";
                ws.Cells[6, 3].Value = "ID trong cơ sở dữ liệu";
                ws.Cells[6, 4].Value = "Tên sản phẩm";
                ws.Cells[6, 5].Value = "Đơn giá";
                ws.Cells[6, 6].Value = "Số lượng nhập";
                ws.Cells[6, 7].Value = "Tổng";

                foreach (var item in ListProduct)
                {
                    if (productService.ImportProduct(item.ProductID, item.Quantity))
                    {
                        ws.Cells[startRow, 1].Value = startRow - 6;
                        ws.Cells[startRow, 2].Value = item.Code;
                        ws.Cells[startRow, 3].Value = item.ProductID;
                        ws.Cells[startRow, 4].Value = item.Name;
                        ws.Cells[startRow, 5].Value = item.Price.ToString("N0");
                        ws.Cells[startRow, 6].Value = item.Quantity;
                        ws.Cells[startRow, 7].Value = (item.Quantity * item.Price).ToString("N0");

                        countProducts++;
                        totalPrice += item.Quantity * item.Price;
                        totalQuantity += item.Quantity;
                        startRow++;
                    }
                }

                ws.Cells["A3:G3"].Value = "Số sản phẩm nhập: " + countProducts;
                ws.Cells["A4:G4"].Value = "Tổng số lượng sản phẩm nhập: " + totalQuantity;
                ws.Cells["A5:G5"].Value = "Tổng tiền nhập: " + totalPrice.ToString("N0");
                ws.Cells.AutoFitColumns();
                pkg.Save();

                var model = new ImportViewModel()
                {
                    Name = HttpContext.Session.GetString("user"),
                    CreatedDate = DateTime.Now,
                    ListImportProductViewModel = ListProduct,
                    Note = "",
                    TotalPrice = totalPrice
                };

                var res = importService.AddImport(model);

                return Json(new { status = (countProducts == ListProduct.Count() && res), filePath = fileName });
            }
            catch (Exception ex)
            {
                return Json(new { status = false, mesage = ex.Message });
            }
        }

        [HttpGet]
        public IActionResult ImportDetail()
        {
            return View();
        }

        public JsonResult ExportExcel()
        {
            string fileName = @"\excel\DanhSachNhapHang-" + DateTime.Now.ToString("MM-dd-yyyy-HH-mm-ss") + "-" + Guid.NewGuid().ToString() + ".xlsx";
            try
            {
                ExcelPackage pkg = new ExcelPackage(new System.IO.FileInfo(webHostEnvironment.WebRootPath + fileName));

                var ws = pkg.Workbook.Worksheets.Add(DateTime.Now.ToString("MM-dd-yyyy-HH-mm-ss"));
                int startRow = 2;
                int count = 1;
                var data = importService.GetImportViewModels();

                ws.Cells[1, 1].Value = "STT";
                ws.Cells[1, 2].Value = "Mã đơn";
                ws.Cells[1, 3].Value = "Người đặt";
                ws.Cells[1, 4].Value = "Ngày đặt";
                ws.Cells[1, 5].Value = "Số loại sản phẩm";
                ws.Cells[1, 6].Value = "Tổng số lượng";
                ws.Cells[1, 7].Value = "Tổng tiền";
                ws.Cells[1, 8].Value = "Ghi chú";

                foreach (var item in data)
                {
                    ws.Cells[startRow, 1].Value = count++;
                    ws.Cells[startRow, 2].Value = item.ID;
                    ws.Cells[startRow, 3].Value = item.Name;
                    ws.Cells[startRow, 4].Value = item.CreatedDate.GetValueOrDefault().ToString("MM/dd/yyyy HH:mm:ss");
                    ws.Cells[startRow, 5].Value = item.CountProduct;
                    ws.Cells[startRow, 6].Value = item.TotalQuantity;
                    ws.Cells[startRow, 7].Value = item.TotalPrice.GetValueOrDefault(0).ToString("N0");
                    ws.Cells[startRow, 8].Value = item.Note;
                    startRow++;
                }
                ws.Cells.AutoFitColumns();
                pkg.Save();
                return Json(new { status = true, filePath = fileName });
            }
            catch (Exception ex)
            {
                return Json(new { status = false, message = ex.Message });
            }
        }
    }
}

Web/Areas/Administrator/Views/Import/ImportDetail.cshtml
@model Entities.DTOs.OrderAdminViewModel

@{
    ViewData["Title"] = "Chi tiết đơn hàng: " + Model.OrderCode;
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="card card-success">
            <!-- /.card-header -->
            <!-- form start -->
            <form action="@Url.Action("Create")" method="post">
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="OrderStatusName" class="control-label">Trạng thái đặt hàng</label>
                        <input asp-for="OrderStatusName" class="form-control" />
                        <span asp-validation-for="OrderStatusName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CustomerFullName" class="control-label">Họ và tên khách hàng</label>
                        <input asp-for="CustomerFullName" class="form-control" />
                        <span asp-validation-for="CustomerFullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CustomerPhone" class="control-label">Số điện thoại khách hàng</label>
                        <input asp-for="CustomerPhone" class="form-control" />
                        <span asp-validation-for="CustomerPhone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CustomerEmail" class="control-label">Email khách hàng</label>
                        <input asp-for="CustomerEmail" class="form-control" type="email" />
                        <span asp-validation-for="CustomerEmail" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CustomerAddress" class="control-label">Địa chỉ khách hàng</label>
                        <input asp-for="CustomerAddress" class="form-control" />
                        <span asp-validation-for="CustomerAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CustomerNote" class="control-label">Ghi chú đặt hàng</label>
                        <textarea asp-for="CustomerNote" class="form-control"></textarea>
                        <span asp-validation-for="CustomerNote" class="text-danger"></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-8 col-sm-6 col-xs-12">
        <div class="card card-success">
            <!-- /.card-header -->
            <!-- form start -->
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <label class="control-label">Danh sách sản phẩm</label>
                    </div>
                    <div class="col-md-12">
                        <table id="example1" class="table table-bordered table-striped dataTable dtr-inline" role="grid" aria-describedby="example1_info">
                            <thead>
                                <tr role="row">
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">STT</th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Mã sản phẩm</th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Tên sản phẩm</th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Giá tiền</th>
                                    <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1">Số lượng</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.ListOrderDetails != null)
                                {
                                    if (Model.ListOrderDetails.Count() > 0)
                                    {
                                        var id = 1;
                                        foreach (var item in Model.ListOrderDetails)
                                        {
                                            <tr role="row">
                                                <td>@id</td>
                                                <td>@item.ProductId</td>
                                                <td>@item.ProductName</td>
                                                <td>@item.ProductPrice</td>
                                                <td>@item.Quantity</td>
                                            </tr>
                                            id++;
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer float-right">
                <a href="@Url.Action("Index", "Order", new { status = ViewBag.CurrentStatus })" class="btn btn-outline-danger">Quay lại</a>&nbsp;
                @if (Model.OrderStatusId == 1)
                {
                    <span>
                        <a class="btn btn-success" href="@Url.Action("ChangeStatus", new {order = Model.Id, status = 2, current = ViewBag.CurrentStatus})">
                            Xác nhận
                        </a>
                        &nbsp;
                        <a class="btn btn-danger" href="@Url.Action("ChangeStatus", new { order = Model.Id, status = -1, current = ViewBag.CurrentStatus})">
                            Hủy đơn
                        </a>
                    </span>
                }
                else if (Model.OrderStatusId == 2)
                {
                    <span>
                        <a class="btn btn-success" href="@Url.Action("ChangeStatus", new { order = Model.Id, status = 3, current = ViewBag.CurrentStatus})">
                            Xuất kho đi giao
                        </a>
                    </span>
                }
                else if (Model.OrderStatusId == 3)
                {
                    <span>
                        <a class="btn btn-success" href="@Url.Action("ChangeStatus", new { order = Model.Id, status = 4, current = ViewBag.CurrentStatus})">
                            Giao thành công
                        </a>
                        <a class="btn btn-warning" href="@Url.Action("ChangeStatus", new { order = Model.Id, status = -2, current = ViewBag.CurrentStatus})">
                            Giao thất bại
                        </a>
                    </span>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts
{
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2();
            $('select').attr('disabled', true);
            $('textarea').attr('disabled', true);
            $('input').attr('disabled', true);
            $('button').attr('disabled', false);
        });
    </script>
    <script>
        $(function () {
            //Initialize Select2 Elements
            $('.select2').select2();
        });
    </script>
}

Web/Areas/Administrator/Views/Import/ImportProduct.cshtml
@{
    ViewData["Title"] = "Nhập hàng";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
    var listCode = (List<Entities.DTOs.ImportProductViewModel?>)ViewBag.ListImportProduct;
}
<!-- /.card-header -->
<div class="card-body">
    <div id="example1_wrapper" class="dataTables_wrapper dt-bootstrap4">
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width:5%">STT</th>
                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width:10%">Mã SP</th>
                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width:5%">ID</th>
                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width:40%">Tên SP</th>
                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width:10%">Đơn giá (kĐ)</th>
                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width:10%">Số lượng</th>
                            <th class="sorting" tabindex="0" aria-controls="example1" rowspan="1" colspan="1" style="width:10%">Thao tác</th>
                        </tr>
                    </thead>
                    <tbody id="importProductTableBody">
                    </tbody>
                    <tfoot>
                        <tr id="thisRow" style="background-color: #dbdbdb">
                            <td></td>
                            <td class="codeProduct">
                                <input list="listCode" id="waitKeycode" placeholder="---Nhập mã sản phẩm" onkeyup="searchByKeyCode(this.value,waitId,waitName)" style="width: 100%; padding: 5px; display: inline-block; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;" />
                                <datalist id="listCode">
                                    @foreach (var item in listCode)
                                    {
                                        <option value="@item.Code"></option>
                                    }
                                </datalist>
                            </td>
                            <td id="waitId" class="idProduct"></td>
                            <td id="waitName" class="nameProduct"></td>
                            <td><input id="waitPrice" value="0" min="0" type="number" style="width: 100%; padding: 5px; display: inline-block; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;" /></td>
                            <td><input id="waitQuantity" value="0" type="number" min="0" style="width: 100%; padding: 5px; display: inline-block; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;" /></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><button id="addItem" class="btn btn-primary" style="width:100%" onclick="addMoreRow(waitKeycode, waitId, waitName, waitQuantity,waitPrice)">Thêm</button></td>
                            <td colspan="5" id="mes" style="color:red"></td>
                            <td>
                                <button class="btn btn-success" onclick="sendReq()">
                                    Nhập hàng
                                </button>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- /.card-body -->
<script type="text/javascript">
    var count = 1;
    function addMoreRow(k, i, n, q,p) {
        if (k.value == "" || i.innerHTML == "" || n.innerHTML == "") {
            document.getElementById("mes").innerHTML = "Thông tin nhập hàng chưa đủ";
        }
        else if (q.value <= 0) {
            document.getElementById("mes").innerHTML = "Nhập số lượng";
        }
        else if (p.value<=0)
        {
            document.getElementById("mes").innerHTML = "Nhập đơn giá";
        }
        else
        {
            var tableBody = document.getElementById("importProductTableBody");
            var row = document.createElement('tr');
            row.id = k.value;
            row.innerHTML = `<tr>
                            <td contenteditable="false">`+ count + `</td>
                            <td contenteditable="false">`+ k.value + `</td>
                            <td contenteditable="false">`+ i.innerHTML + `</td>
                            <td contenteditable="false">`+ n.innerHTML + `</td>
                            <td contenteditable="false" type="number"><input value="`+ p.value + `" min="0" type="number" style="width: 100%; padding: 5px; display: inline-block; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;"/></td>
                            <td contenteditable="false" type="number"><input value="`+ q.value + `" min="0" type="number" style="width: 100%; padding: 5px; display: inline-block; border: 1px solid #ccc; border-radius: 5px; box-sizing: border-box;"/></td>
                        </tr>`;
            tableBody.innerHTML = tableBody.innerHTML + row.innerHTML;
            count++;
            i.innerHTML = n.innerHTML = "";
            k.value = ""; q.value = 0; p.value = 0;
        }
    }

    function deleteImportItem(obj) {
       obj.parentElement.parentElement.remove();
    }

    function searchByKeyCode(value,i,n) {
        $.ajax({
            url: "@Url.Action("SearchProductByKeyCode", "Product")",
            data: { keyCode: value },
            type: 'POST',
            dataType: 'json',
            success: function (res) {

                if (res.status == true) {
                    i.innerHTML = res.obj.ProductID;
                    n.innerHTML = res.obj.Name;
                    document.getElementById("mes").innerHTML = "";
                }
                else {
                    i.innerHTML = "";
                    n.innerHTML = "";
                    document.getElementById("mes").innerHTML = res.message;
                }
            }
        });
    }

    function sendReq() {
        document.getElementById("mes").innerHTML = 'Sau khi nhập hành thành công, hệ thống sẽ gửi file Excel nhập hàng!';
        var listObj = [];
        var list = document.getElementById("importProductTableBody").rows;
        var length = list.length;
        for (i = 0; i < length; i++) {
            var obj = {};
            obj.ProductID = parseInt(list[i].cells[2].innerHTML);
            obj.Quantity = parseInt(list[i].cells[5].children[0].value);
            obj.Code = list[i].cells[1].innerHTML;
            obj.Name = list[i].cells[3].innerHTML;
            obj.Price = parseInt(list[i].cells[4].children[0].value+"000");
            listObj.push(obj);
        };
        $.ajax({
            url: "@Url.Action("ImportProduct","Import")",
            data: { jsonString: JSON.stringify(listObj) },
            type: "POST",
            dataType: "json",
            success: function (res) {
                if (res.status == true) {
                    window.location.href = res.filePath;
                }
                else {
                    alert("Có lỗi xảy ra vui lòng nhập hàng lại")
                }
            }
        });
    }
</script>